parametrosCompilacao=-Wall  #-Wshadow
nomePrograma=trab

all: trab

$(nomePrograma): main.o ordenacao.o
	gcc -o trab main.o ordenacao.o $(parametrosCompilacao)

main.o: main.c
	gcc -c main.c $(parametrosCompilacao)

ordenacao.o: ordenacao.h ordenacao.c
	gcc -c ordenacao.c $(parametrosCompilacao)

clean:
	rm -f *.o *.gch $(nomePrograma)